services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
    depends_on:
      - app
      - mysql
    networks:
      - network_webapp
  app:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    networks:
      - network_webapp
  mysql:
    image: mysql:8.0.32
    restart: always
    ports:
      - "3316:3306"
    env_file:
      - env/mysql.env
    volumes:
      - albums_db_data:/var/lib/mysql
    command: --authentication_policy=mysql_native_password
    networks:
      - network_webapp
  mysql_test:
    image: mysql:8.0.32
    restart: always
    ports:
      - "3317:3306"
    env_file:
      - env/mysql_test.env
    volumes:
      - albums_test_db_data:/var/lib/mysql
    command: --authentication_policy=mysql_native_password
    networks:
      - network_webapp

networks:
  network_webapp:

volumes:
  albums_db_data:
  albums_test_db_data:
